const topics=window.EVS_TOPICS||[]; const questions=window.EVS_QUESTIONS||[];
const nav=document.getElementById('topicNav'),content=document.getElementById('content'),practice=document.getElementById('practice');
const done=JSON.parse(localStorage.getItem('evsDone')||'{}'),groups=[...new Set(topics.map(t=>t.group))];
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function cardList(items){return '<ul>'+items.map(x=>'<li>'+x+'</li>').join('')+'</ul>'}
function flow(t){return '<div class="visual-flow">'+t.flow.map((x,j)=>'<div class="flow-step">'+esc(x)+'</div>'+(j<t.flow.length-1?'<div class="flow-arrow">→</div>':'')).join('')+'</div>'}
function table(t){if(!t.table)return '';return '<div class="table-wrap"><table class="mini-table"><thead><tr>'+t.table[0].map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+t.table.slice(1).map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
function renderNav(){nav.innerHTML=groups.map(g=>'<div class="nav-group">'+esc(g)+'</div>'+topics.map((t,i)=>t.group===g?'<button class="topic-link '+(done[i]?'done':'')+'" data-id="'+i+'"><span class="topic-num">'+String(i+1).padStart(2,'0')+'</span><span class="topic-link-text">'+esc(t.title)+'</span><span class="topic-dot"></span></button>':'').join('')).join('');nav.querySelectorAll('.topic-link').forEach(b=>b.onclick=()=>{nav.querySelectorAll('.topic-link').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('topic-'+b.dataset.id)?.scrollIntoView({behavior:'smooth',block:'start'});if(innerWidth<900){document.getElementById('sidebar').classList.remove('open');document.getElementById('menuBtn').setAttribute('aria-expanded','false')}})}
let currentTopics=topics;
function renderTopics(list=topics){
 if(!list.length){content.innerHTML='<div class="empty-state"><div class="empty-icon">⌕</div><strong>No topics found</strong><span>Try a broader term, Act name, number, or clear the search.</span></div>';return}
 content.innerHTML='<div class="study-intro"><div><span class="section-kicker">COURSE NOTES</span><h2>High-yield revision sheet</h2><p>Read the facts first, then use the visual and table to lock the concept in.</p></div><span class="topic-total">'+list.length+' topic'+(list.length===1?'':'s')+'</span></div>'+list.map(t=>{const i=topics.indexOf(t);return '<article class="topic" id="topic-'+i+'"><div class="topic-head"><div class="topic-title"><div class="num">'+String(i+1).padStart(2,'0')+'</div><div><div class="topic-kicker">'+esc(t.group)+'</div><h2>'+esc(t.title)+'</h2><div class="topic-sub">'+esc(t.sub)+'</div></div></div><div class="topic-tools"><span class="priority '+(t.p==='high'?'high':t.p==='med'?'med':'low')+'">'+(t.p==='high'?'HIGH YIELD':t.p==='med'?'MEDIUM':'QUICK SCAN')+'</span><button class="check '+(done[i]?'done':'')+'" aria-label="'+(done[i]?'Mark unfinished':'Mark revised')+'" data-check="'+i+'">'+(done[i]?'✓':'○')+'</button></div></div><div class="topic-layout"><div class="learn-column"><section class="study-card key-card"><div class="card-label"><span class="label-mark">01</span>KNOW THIS</div>'+cardList(t.must)+'</section><section class="study-card trap-card"><div class="card-label"><span class="label-mark warn">02</span>MCQ TRAPS</div>'+cardList(t.traps)+'</section>'+(t.note?'<div class="note-strip"><span>NOTE</span>'+esc(t.note)+'</div>':'')+'</div><div class="visual-column"><section class="study-card diagram-card"><div class="card-label"><span class="label-mark cyan">03</span>VISUAL MEMORY</div>'+flow(t)+table(t)+'</section></div></div></article>'}).join('');
 content.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const i=b.dataset.check;done[i]=!done[i];localStorage.setItem('evsDone',JSON.stringify(done));renderNav();renderTopics(currentTopics);updateProgress()});
}
function updateProgress(){const n=Object.values(done).filter(Boolean).length;document.getElementById('progressCount').textContent=n+'/'+topics.length;document.getElementById('progressLabel').textContent=Math.round(n/topics.length*100)+'% revised';document.getElementById('progressBar').style.width=n/topics.length*100+'%'}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function showPractice(){practice.classList.remove('hidden');content.classList.add('hidden');const selected=shuffle([...questions]).slice(0,30);practice.innerHTML='<div class="practice-box"><div class="study-intro"><div><span class="section-kicker">ACTIVE RECALL</span><h2>30-question rapid test</h2><p>Answer first. The correct option appears only after you commit.</p></div><div id="score" class="score">0 / 30</div></div>'+selected.map((q,i)=>'<div class="q"><p><span class="q-number">'+String(i+1).padStart(2,'0')+'</span>'+esc(q[0])+'</p><div class="options">'+q[1].map((o,j)=>'<button class="opt" data-q="'+i+'" data-a="'+j+'">'+String.fromCharCode(65+j)+'. '+esc(o)+'</button>').join('')+'</div><div class="answer"></div></div>').join('')+'</div>';let score=0;[...practice.querySelectorAll('.q')].forEach((box,i)=>box.querySelectorAll('.opt').forEach(btn=>btn.onclick=()=>{if(box.dataset.answered)return;box.dataset.answered='1';const c=selected[i][2],a=Number(btn.dataset.a);box.querySelectorAll('.opt').forEach((o,k)=>{if(k===c)o.classList.add('correct')});if(a===c){btn.classList.add('correct');score++}else btn.classList.add('wrong');box.querySelector('.answer').textContent=a===c?'Correct.':'Wrong — correct answer highlighted.';document.getElementById('score').textContent=score+' / 30'}))}
function showFlashcards(){practice.classList.remove('hidden');content.classList.add('hidden');const pool=topics.flatMap((t,ti)=>t.must.map((fact,fi)=>({topic:t.title,fact,ti,fi})));let index=0,known=0;function draw(){const c=pool[index];practice.innerHTML='<div class="flash-shell"><div class="study-intro"><div><span class="section-kicker">ACTIVE RECALL</span><h2>Flashcards</h2><p>Read the prompt, recall the fact, then reveal.</p></div><span class="topic-total">'+(index+1)+' / '+pool.length+'</span></div><div class="flashcard"><div class="flash-meta">'+esc(c.topic)+'</div><div class="flash-question">Can you recall this?</div><div class="flash-prompt">'+esc(c.fact)+'</div><button class="reveal-btn" id="reveal">Reveal answer</button><div class="flash-answer hidden" id="flashAnswer">This is a must-remember point from the supplied course notes.</div></div><div class="flash-controls"><button class="secondary" id="prevCard">← Previous</button><button class="secondary" id="skipCard">Skip</button><button class="primary" id="knowCard">✓ I know this</button></div><div class="flash-progress"><i style="width:'+((index+1)/pool.length*100)+'%"></i></div><div class="flash-count">'+known+' cards marked known</div></div>';document.getElementById('reveal').onclick=()=>document.getElementById('flashAnswer').classList.toggle('hidden');document.getElementById('prevCard').onclick=()=>{index=(index-1+pool.length)%pool.length;draw()};document.getElementById('skipCard').onclick=()=>{index=(index+1)%pool.length;draw()};document.getElementById('knowCard').onclick=()=>{known++;index=(index+1)%pool.length;draw()}}draw()}
renderNav();renderTopics();updateProgress();
document.getElementById('practiceBtn').onclick=showPractice;
document.getElementById('flashBtn').onclick=showFlashcards;
document.getElementById('startBtn').onclick=()=>document.getElementById('topic-0').scrollIntoView({behavior:'smooth'});
document.getElementById('randomBtn').onclick=()=>document.getElementById('topic-'+Math.floor(Math.random()*topics.length)).scrollIntoView({behavior:'smooth'});
document.getElementById('reviewBtn').onclick=()=>document.getElementById('topic-0').scrollIntoView({behavior:'smooth'});
document.getElementById('menuBtn').onclick=()=>{const sidebar=document.getElementById('sidebar');const open=!sidebar.classList.contains('open');sidebar.classList.toggle('open',open);document.getElementById('menuBtn').setAttribute('aria-expanded',String(open))};
document.getElementById('search').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();currentTopics=q?topics.filter(t=>JSON.stringify(t).toLowerCase().includes(q)):topics;renderTopics(currentTopics)});
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('search').focus()}});
