const topics=window.EVS_TOPICS||[]; const questions=window.EVS_QUESTIONS||[];
const nav=document.getElementById('topicNav'),content=document.getElementById('content'),practice=document.getElementById('practice');
const done=JSON.parse(localStorage.getItem('evsDone')||'{}'),groups=[...new Set(topics.map(t=>t.group))];
function renderNav(){nav.innerHTML=groups.map(g=>'<div class="nav-group">'+g+'</div>'+topics.map((t,i)=>t.group===g?'<button class="topic-link '+(done[i]?'done':'')+'" data-id="'+i+'"><span class="dot"></span>'+t.title+'</button>':'').join('')).join('');nav.querySelectorAll('.topic-link').forEach(b=>b.onclick=()=>{document.getElementById('topic-'+b.dataset.id)?.scrollIntoView({behavior:'smooth'});if(innerWidth<900)document.getElementById('sidebar').classList.remove('open')})}
function cardList(items){return '<ul>'+items.map(x=>'<li>'+x+'</li>').join('')+'</ul>'}
function renderTopics(list=topics){content.innerHTML=list.map(t=>{const i=topics.indexOf(t);return '<article class="topic" id="topic-'+i+'"><div class="topic-head"><div class="topic-title"><div class="num">'+String(i+1).padStart(2,'0')+'</div><div><h2>'+t.title+'</h2><div class="topic-sub">'+t.sub+'</div></div></div><div style="display:flex;gap:7px;align-items:center"><span class="priority '+(t.p==='high'?'high':t.p==='med'?'med':'low')+'">'+(t.p==='high'?'HIGH YIELD':t.p==='med'?'MEDIUM':'QUICK SCAN')+'</span><button class="check '+(done[i]?'done':'')+'" data-check="'+i+'">'+(done[i]?'✓':'○')+'</button></div></div><div class="section-grid"><div><div class="card must"><h3>MEMORISE THIS</h3>'+cardList(t.must)+'</div><div class="card trap" style="margin-top:12px"><h3>MCQ TRAPS</h3>'+cardList(t.traps)+'</div>'+(t.note?'<div class="callout">'+t.note+'</div>':'')+'</div><div><div class="card visual"><h3>VISUAL RECALL</h3><div class="flow">'+t.flow.map((x,j)=>'<span class="node">'+x+'</span>'+(j<t.flow.length-1?'<span class="arrow">→</span>':'')).join('')+'</div>'+(t.table?'<table class="mini-table" style="margin-top:15px"><thead><tr>'+t.table[0].map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+t.table.slice(1).map(r=>'<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table>':'')+'</div></div></div></article>'}).join('');content.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const i=b.dataset.check;done[i]=!done[i];localStorage.setItem('evsDone',JSON.stringify(done));renderNav();renderTopics();updateProgress()})}
function updateProgress(){const n=Object.values(done).filter(Boolean).length;document.getElementById('progressCount').textContent=n+'/'+topics.length;document.getElementById('progressLabel').textContent=Math.round(n/topics.length*100)+'% revised';document.getElementById('progressBar').style.width=n/topics.length*100+'%'}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function showPractice(){practice.classList.remove('hidden');content.classList.add('hidden');const selected=shuffle([...questions]).slice(0,30);practice.innerHTML='<div class="practice-box"><h2>⚡ 30-question rapid test</h2><p class="topic-sub">Pick an answer. Your score updates live.</p><div id="score" class="score">Score: 0 / 30</div>'+selected.map((q,i)=>'<div class="q"><p>'+i+'. '+q[0]+'</p><div class="options">'+q[1].map((o,j)=>'<button class="opt" data-q="'+i+'" data-a="'+j+'">'+String.fromCharCode(65+j)+'. '+o+'</button>').join('')+'</div><div class="answer"></div></div>').join('')+'</div>';let score=0;const boxes=[...practice.querySelectorAll('.q')];boxes.forEach((box,i)=>box.querySelectorAll('.opt').forEach(btn=>btn.onclick=()=>{if(box.dataset.answered)return;box.dataset.answered='1';const c=selected[i][2],a=Number(btn.dataset.a);box.querySelectorAll('.opt').forEach((o,k)=>{if(k===c)o.classList.add('correct')});if(a===c){btn.classList.add('correct');score++}else btn.classList.add('wrong');box.querySelector('.answer').textContent=a===c?'Correct.':'Wrong — correct answer highlighted.';document.getElementById('score').textContent='Score: '+score+' / 30'}))}
renderNav();renderTopics();updateProgress();
document.getElementById('practiceBtn').onclick=showPractice;
document.getElementById('startBtn').onclick=()=>document.getElementById('topic-0').scrollIntoView({behavior:'smooth'});
document.getElementById('randomBtn').onclick=()=>document.getElementById('topic-'+Math.floor(Math.random()*topics.length)).scrollIntoView({behavior:'smooth'});
document.getElementById('reviewBtn').onclick=()=>document.getElementById('topic-0').scrollIntoView({behavior:'smooth'});
document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
document.getElementById('search').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();renderTopics(q?topics.filter(t=>JSON.stringify(t).toLowerCase().includes(q)):topics)});
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('search').focus()}});